WebApplicationSolution/WebApplicationDemo2023/Models/Facture.cs
using System;
using System.Collections.Generic;

namespace WebApplicationDemo2023.Models
{
    public partial class Facture
    {
        public Facture()
        {
            LigneFactures = new HashSet<LigneFacture>();
        }

        public int Id { get; set; }
        public DateTime DateFacture { get; set; }
        public int ClientId { get; set; }

        public string MontantTotalCHF { get { return LigneFactures.Sum(x => x.Quantite * x.PrixUnitaire) + " CHF"; } }

        public virtual Client Client { get; set; } = null!;
        public virtual ICollection<LigneFacture> LigneFactures { get; set; }
        public int? UtilisateurId { get; set; }

        
    }
}

WebApplicationSolution/WebApplicationDemo2023/Controllers/FacturesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using WebApplicationDemo2023.Models;

namespace WebApplication2.Controllers
{
    public class FacturesController : Controller
    {
        private readonly SqlServerContext _context;

        public FacturesController(SqlServerContext context)
        {
            _context = context;
        }

        // GET: Factures
        public async Task<IActionResult> Index()
        {
            string role = User.Claims.FirstOrDefault(x => x.Type == "Role").Value;
            int id = int.Parse(User.Claims.FirstOrDefault(x => x.Type == "Id").Value);
            var maliste = _context.Factures.Include(f => f.Client).Include(f => f.LigneFactures).ToList();
            if (role == "user")
            {
                maliste = maliste.Where(x => x.UtilisateurId == id).ToList();
            }
            return View(maliste);
        }

        // GET: Factures/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Factures == null)
            {
                return NotFound();
            }

            var facture = await _context.Factures
                .Include(f => f.Client)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (facture == null)
            {
                return NotFound();
            }

            return View(facture);
        }

        // GET: Factures/Create
        public IActionResult Create()
        {
            //création de la liste des clients
            List<SelectListItem> listClients = new List<SelectListItem>();
            foreach (Client c in _context.Clients)
            {
                listClients.Add(new SelectListItem() { Text = c.Prenom + " " + c.Nom, Value = c.Id.ToString() });
            }
            ViewData["Clients"] = listClients;
            //transformation de la liste des articles en json pour javascript plus tard
            ViewBag.ArticlesJson = JsonConvert.SerializeObject(_context.Articles);
            return View(new Facture() { DateFacture = DateTime.Now});
        }

        // POST: Factures/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("Id,Numero,DateFacture,ClientId,Actif")] Facture facture, List<LigneFacture> LignesFacture, string Numero, DateTime DateFacture, int ClientId)
        //{
        //    //var LignesFacture = ViewBag.LignesFacture;
        //    if (ModelState.IsValid)
        //    {
        //        _context.Add(facture);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    ViewData["ClientId"] = new SelectList(_context.Clients, "Id", "Localite", facture.ClientId);
        //    return View(facture);
        //}

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<bool> CreateNewFacture(List<LigneFacture> LignesFacture, DateTime DateFacture, int ClientId)
        {
            Facture facture = new Facture();
            facture.DateFacture = DateFacture;
            facture.ClientId = ClientId;
            facture.LigneFactures = LignesFacture; ;
            _context.Add(facture);
            await _context.SaveChangesAsync();
            return true;
        }

        // GET: Factures/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Factures == null)
            {
                return NotFound();
            }

            var facture = await _context.Factures.FindAsync(id);
            if (facture == null)
            {
                return NotFound();
            }
            List<SelectListItem> listClients = new List<SelectListItem>();
            foreach(Client c in _context.Clients)
            {
                listClients.Add(new SelectListItem() { Text = c.Prenom + " " + c.Nom, Value = c.Id.ToString() });
            }
            listClients.Add(new SelectListItem() { Text = "Veuillez sélectionner un client", Value = "" });
            ViewData["ClientId"] = listClients;
            return View(facture);
        }

        // POST: Factures/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Numero,DateFacture,ClientId,Actif")] Facture facture)
        {
            if (id != facture.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(facture);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FactureExists(facture.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClientId"] = new SelectList(_context.Clients, "Id", "Localite", facture.ClientId);
            return View(facture);
        }

        // GET: Factures/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Factures == null)
            {
                return NotFound();
            }

            var facture = await _context.Factures
                .Include(f => f.Client)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (facture == null)
            {
                return NotFound();
            }

            return View(facture);
        }

        // POST: Factures/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Factures == null)
            {
                return Problem("Entity set 'MonContext.Factures'  is null.");
            }
            var facture = await _context.Factures.FindAsync(id);
            if (facture != null)
            {
                _context.Factures.Remove(facture);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FactureExists(int id)
        {
          return _context.Factures.Any(e => e.Id == id);
        }
    }
}

WebApplicationSolution/WebApplicationDemo2023/Controllers/PrintController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplicationDemo2023.Models;

namespace WebApplicationDemo2023.Controllers
{
    public class PrintController : Controller
    {
        private readonly SqlServerContext _context;
        public IActionResult Print(int factureId)
        {
            Facture f = _context.Factures.Include(y => y.LigneFactures).
                ThenInclude(a => a.Article).
                Include(c => c.Client).
                FirstOrDefault(x => x.Id == factureId);
            string templateChemin = "C:\\Users\\Yves\\github\\csharp2023\\WebApplicationSolution\\WebApplicationDemo2023\\template\\facture_template.docx";
            string pdf = WebApplicationDemo2023.Helpers.Print.CreerDocumentAPartirDuTemplate(f, templateChemin);
            byte[] pdfBytes = System.IO.File.ReadAllBytes(pdf);
            MemoryStream ms = new MemoryStream(pdfBytes);
            return new FileStreamResult(ms, "application/pdf");

        }

        public PrintController(SqlServerContext context)
        {
            _context = context;
        }
    }
}

WebApplicationSolution/WebApplicationDemo2023/Views/Factures/Create.cshtml
@using Newtonsoft.Json;
@model WebApplicationDemo2023.Models.Facture;

@{
    ViewData["Title"] = "Create";
}
<h4>Création d'une facture</h4>
<hr />
@*<form asp-action="Create" onsubmit="return GetLignesFacture()">*@
<div class="container">
    @*pour aligner à gauche (pas que ça soit réparti sur toute la largeur*@
        <div class="d-inline-flex align-items-start">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @* me-5 pour laisser un margin entre les composants*@

            <div class="col-sm  me-5">
            <div class="form-group">
                <label asp-for="DateFacture" class="control-label"></label>
                <input asp-for="DateFacture" class="form-control widthAuto" />
                <span asp-validation-for="DateFacture" class="text-danger"></span>
            </div>
    </div>
    <div class="col-sm">
            <div class="form-group">
                <label asp-for="ClientId" class="control-label"></label>
                <select asp-for="ClientId" class="form-control widthAuto" asp-items="ViewBag.Clients">
                    <option value="" selected="selected">[Veuillez sélectionner un client]</option>
                </select>
                <span asp-validation-for="ClientId" class="text-danger"></span>
            </div>
    </div>
  </div>
  <br/>
        <div class="d-inline-flex align-items-start mt-4">
    <div class="col-sm me-5">
            <div class="form-group">
                <select id="Articles"
                        name="Articles"
                        class="form-control widthAuto"
                        size="10">
                    @{
                        List<Article> listArticles = JsonConvert.DeserializeObject<List<Article>>(ViewBag.ArticlesJson);
                    }
                    @foreach (Article a in listArticles)
                        {
                            <option value="@a.Id">@a.Nom</option>
                        }
                </select>
            </div>
    </div>
    <div class="col-sm">
            <div class="form-group">
                <input type="hidden" id="IdArticleToAdd" value=""/>
                N° Article :
                <input type="text" readonly="readonly" id="Num" value="" class="form-control widthAuto" />
                
                Nom :
                <input type="text" readonly="readonly" id="Nom" value="" class="form-control widthAuto" />

                Quantité :
                <input type="number" min="1" id="Quantite" value="" class="form-control widthAuto" />

                Prix unitaire :
                <input type="number" min="1" id="PrixUnitaire" value="" class="form-control widthAuto" />
                <br/>
                <!--TODO on est dans un form, pour les boutons qui appelle du javascript il ne faut pas leur donner d'id ou name-->
                    <input type="button" class="btn btn-primary" value="Ajouter" onclick="AddArticle()" />
            </div>
    </div>
  </div>
</div>
<div class="row">
        <div class="col-md-4 mt-3">
            
            <table class="table table-striped table-sm" id="TableLignesFacture">
                <thead>
                    <tr><th scope="col">#</th>
                        <th scope="col">Id</th>
                        <th scope="col">Nom</th>
                        <th scope="col">Quantité</th>
                        <th scope="col">Prix</th>
                        <th scope="col">Total</th>
                        <th scope="col">&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach(LigneFacture lf in Model.LigneFactures)
                    {
                        <tr>
                            <th scope="row">@lf.Id</th>
                            <td>@lf.Article.Id</td>
                            <td>@lf.Article.Nom</td>
                            <td>@lf.Quantite</td>
                            <td>@lf.PrixUnitaire</td>
                            <td>@lf.MontantTotalCHF</td>
                            <td>delete</td>
                        </tr>
                    }
                </tbody>
            </table>
            <div class="form-group">
            @*<input type="submit" value="Enregistrer" class="btn btn-primary" />*@
            <input type="button" value="Sauver" id="Update" onclick="GetLignesFacture()" />
            </div>
        
    </div>
</div>
@*</form>*@
<div>
    <a asp-action="Index">Back to List</a>
</div>

<script>
    //quand on clique sur un article on affiche les infos dans la partie détail à droite
    const select = document.getElementById('Articles');
    var id = 0;
    var nom = "";
    select.addEventListener('change', function handleChange(event) {
        id = event.target.value;
        //déserialisation de la liste
        var Articles = JSON.parse(@Html.Raw(Json.Serialize(@ViewBag.ArticlesJson)));
        for (var i = 0; i < Articles.length; i++) {
            if (id == Articles[i].Id)
            {
                document.getElementById('IdArticleToAdd').value = Articles[i].Id;
                document.getElementById('Num').value = Articles[i].Id;
                document.getElementById('Nom').value = Articles[i].Nom;
                document.getElementById('Quantite').value = 1;
                document.getElementById('PrixUnitaire').value = Articles[i].Prix;
            }
        }
    });
</script>
<script>
    //ajout d'un article dans le tableau
    //TODO tester que tout soit rempli
    function AddArticle() {
        var id = $("#IdArticleToAdd").val();
        var nom = $("#Nom").val();
        var quantite = $("#Quantite").val();
        var prixUnitaire = $("#PrixUnitaire").val();
        if (id == '' || nom == '' || quantite == 0 || quantite == '' || prixUnitaire == 0 || prixUnitaire == '')
        {
            alert(id + '/' + nom + '/' + quantite + '/' + prixUnitaire);
        } else {
            var tr = "<tr><td>-</td><td>" + id + "</td><td>" + nom + "</td><td>" + quantite + "</td><td>" + prixUnitaire + "</td><td>" + (quantite * prixUnitaire) + "</td><td>X</td></tr>";
        $("#TableLignesFacture").append(tr);
        }  
    }
</script>
<script>
    //récupération des lignes dans la table pour les ajouter à lignes factures
    function GetLignesFacture() {
        var result = [];
        var tr = $("#TableLignesFacture tr");
        for (var i = 1; i < tr.length; i++) {
            var tds = $(tr[i]).find("td");
            if (tds.length > 0) {
                result.push({
                    "ArticleId": tds[1].innerHTML,
                    "Quantite": tds[3].innerHTML,
                    "PrixUnitaire": tds[4].innerHTML
                })
            }
        }
        //récupération des données de la nouvelle facture
        var date = document.getElementById('DateFacture').value;
        var client = document.getElementById('ClientId').value;
        var jsonData = {
                "LignesFacture": result,
                "DateFacture": date,
                "ClientId": client
            }
            $.ajax({
                dataType: 'json',
                type: "Post",
                data: jsonData,
            url: "/Factures/CreateNewFacture",
                success: function (html) {
                // recharge la page pour afficher les factures
                window.location.replace("/Factures/Index");
                }
            })
    }
</script>
@section Scripts {
    

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    
}

WebApplicationSolution/WebApplicationDemo2023/Views/Factures/Index.cshtml
@model List<Facture>

<h1>Liste des factures</h1>
<partial name="Message" />


<br/>
<a asp-controller="Factures" asp-action="Create" class="btn btn-primary">Créer une nouvelle Facture</a>
<table class="table table-striped table-bordered">
    <thead>
        <tr>
        <th>N°</th>
    <th>Date</th>
    <th>Client</th>
            <th>Nombre d'articles</th>
            <th>Total</th>
    <th></th>
    </tr>
    </thead>
    <tbody>
        @{
            foreach(Facture f in Model)
            {
                <tr>
                    <td width="5%">@f.Id</td>
                    <td width="5%">@f.DateFacture</td>
                    <td width="5%">@f.Client.Prenom</td>
                    <td width="5%">@f.LigneFactures.Sum(x => x.Quantite)</td>
                    <td width="5%">@f.MontantTotalCHF</td>
                    <td width="5%"><a asp-controller="Print" asp-action="Print" asp-route-factureId="@f.Id" target="_blank" class="btn btn-primary mx-2">Imprimer</a></td>
                </tr>
            }
        }
        
    </tbody>
</table>