WebApplicationSolution/WebApplicationDemo2023/Controllers/ArticleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplicationDemo2023.Models;

namespace WebApplicationDemo2023.Controllers
{
    [Authorize(Roles = "admin")]
    public class ArticleController : Controller
    {
        private SqlServerContext _con;

        public ArticleController(SqlServerContext connection)
        {
            _con = connection;
        }

        private void LoadListCategorie()
        {
            List<Categorie> listCat = _con.Categories.ToList();
            List<SelectListItem> list = new List<SelectListItem>();
            foreach (Categorie cat in listCat)
            {
                SelectListItem item = new SelectListItem();
                item.Text = cat.Nom;
                item.Value = cat.Id.ToString();
                list.Add(item);
            }
            
            ViewBag.ListCAT = list;
        }


        public IActionResult Index()
        {
            List<Article> listeArt = _con.Articles.Include(a => a.Categorie).ToList();
            return View(listeArt);
        }

        public IActionResult Create()
        {
            LoadListCategorie();
            return View("Update", new Article() { Id = 0});
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Article a)
        {
            if (ModelState.IsValid)
            {
                _con.Articles.Add(a);
                _con.SaveChanges();
                TempData["messageOK"] = "youpie l'article est ajoutée";
                return RedirectToAction("Index");
            }
            return View("Update", a);
        }

        public IActionResult Update(int id)
        {
            Article a = _con.Articles.FirstOrDefault(a => a.Id == id);
            if (a == null)
            {
                TempData["messageKO"] = "l'article souhaité n'existe pas";
                return RedirectToAction("Index");
            } else {
                LoadListCategorie();
                return View(a);
            }
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Article a)
        {
            if (ModelState.IsValid)
            {
                _con.Articles.Update(a);
                _con.SaveChanges();
                TempData["messageOK"] = "youpie l'article est modifié";
                return RedirectToAction("Index");
            }
            return View(a);
        }
    }
}

WebApplicationSolution/WebApplicationDemo2023/Controllers/CategorieController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApplicationDemo2023.Models;

namespace WebApplicationDemo2023.Controllers
{
    [Authorize]
    public class CategorieController : Controller
    {
        private readonly ILogger<CategorieController> _logger;
        private SqlServerContext _con;

        public CategorieController(ILogger<CategorieController> logger, SqlServerContext connection)
        {
            _logger = logger;
            _con = connection;
        }

        public IActionResult Index()
        {
            List<Categorie> listeCat = _con.Categories.ToList();
            return View(listeCat);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Categorie c)
        {
            if (ModelState.IsValid)
            {
                _con.Categories.Add(c);
                _con.SaveChanges();
                TempData["messageOK"] = "youpie la catégorie est ajoutée";
                return RedirectToAction("Index");
            }
            return View(c);
        }

        public IActionResult Update(int id)
        {
            //Categorie c = _con.Categories.Find(id);
            Categorie c = _con.Categories.FirstOrDefault(c => c.Id == id);
            if (c == null)
            {
                TempData["messageKO"] = "la catégorie souhaitée n'existe pas";
                return RedirectToAction("Index");
            } else {
                return View(c);
            }
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Categorie c)
        {
            if (ModelState.IsValid)
            {
                _con.Categories.Update(c);
                _con.SaveChanges();
                TempData["messageOK"] = "youpie la catégorie est modifiée";
                return RedirectToAction("Index");
            }
            return View(c);
        }
    }
}

WebApplicationSolution/WebApplicationDemo2023/Controllers/ClientController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApplicationDemo2023.Models;

namespace WebApplicationDemo2023.Controllers
{
    [Authorize]
    public class ClientController : Controller
    {
        private readonly ILogger<ClientController> _logger;
        private SqlServerContext _con;

        public ClientController(ILogger<ClientController> logger, SqlServerContext connection)
        {
            _logger = logger;
            _con = connection;
        }

        private void LoadListNPA()
        {
            List<string> listNpa = _con.Clients.Select(x => x.Npa).ToList();
            List<SelectListItem> list = new List<SelectListItem>();
            foreach (string npa in listNpa)
            {
                SelectListItem item = new SelectListItem();
                item.Text = npa;
                item.Value = npa;
                list.Add(item);
            }
            
            ViewBag.ListNPA = list;
        }


        public IActionResult Index()
        {
            List<Client> listeCli = _con.Clients.ToList();
            return View(listeCli);
        }

        public IActionResult Create()
        {
            LoadListNPA();
            return View("Update", new Client() { Id = 0});
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Client c)
        {
            if (ModelState.IsValid)
            {
                _con.Clients.Add(c);
                _con.SaveChanges();
                TempData["messageOK"] = "youpie le client est ajoutée";
                return RedirectToAction("Index");
            }
            return View("Update", c);
        }

        public IActionResult Update(int id)
        {
            Client c = _con.Clients.FirstOrDefault(c => c.Id == id);
            if (c == null)
            {
                TempData["messageKO"] = "le client souhaité n'existe pas";
                return RedirectToAction("Index");
            } else {
                LoadListNPA();
                return View(c);
            }
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Client c)
        {
            if (ModelState.IsValid)
            {
                _con.Clients.Update(c);
                _con.SaveChanges();
                TempData["messageOK"] = "youpie le client est modifié";
                return RedirectToAction("Index");
            }
            return View(c);
        }
    }
}

WebApplicationSolution/WebApplicationDemo2023/Controllers/FacturesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using WebApplicationDemo2023.Models;

namespace WebApplication2.Controllers
{
    public class FacturesController : Controller
    {
        private readonly SqlServerContext _context;

        public FacturesController(SqlServerContext context)
        {
            _context = context;
        }

        // GET: Factures
        public async Task<IActionResult> Index()
        {
            string role = User.Claims.FirstOrDefault(x => x.Type == "Role").Value;
            int id = int.Parse(User.Claims.FirstOrDefault(x => x.Type == "Id").Value);
            var maliste = _context.Factures.Include(f => f.Client).Include(f => f.LigneFactures).ToList();
            if (role == "user")
            {
                maliste = maliste.Where(x => x.UtilisateurId == id).ToList();
            }
            return View(maliste);
        }

        // GET: Factures/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Factures == null)
            {
                return NotFound();
            }

            var facture = await _context.Factures
                .Include(f => f.Client)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (facture == null)
            {
                return NotFound();
            }

            return View(facture);
        }

        // GET: Factures/Create
        public IActionResult Create()
        {
            //création de la liste des clients
            List<SelectListItem> listClients = new List<SelectListItem>();
            foreach (Client c in _context.Clients)
            {
                listClients.Add(new SelectListItem() { Text = c.Prenom + " " + c.Nom, Value = c.Id.ToString() });
            }
            ViewData["Clients"] = listClients;
            //transformation de la liste des articles en json pour javascript plus tard
            ViewBag.ArticlesJson = JsonConvert.SerializeObject(_context.Articles);
            return View(new Facture() { DateFacture = DateTime.Now});
        }

        // POST: Factures/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("Id,Numero,DateFacture,ClientId,Actif")] Facture facture, List<LigneFacture> LignesFacture, string Numero, DateTime DateFacture, int ClientId)
        //{
        //    //var LignesFacture = ViewBag.LignesFacture;
        //    if (ModelState.IsValid)
        //    {
        //        _context.Add(facture);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    ViewData["ClientId"] = new SelectList(_context.Clients, "Id", "Localite", facture.ClientId);
        //    return View(facture);
        //}

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<bool> CreateNewFacture(List<LigneFacture> LignesFacture, DateTime DateFacture, int ClientId)
        {
            Facture facture = new Facture();
            facture.DateFacture = DateFacture;
            facture.ClientId = ClientId;
            facture.LigneFactures = LignesFacture; ;
            _context.Add(facture);
            await _context.SaveChangesAsync();
            return true;
        }

        // GET: Factures/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Factures == null)
            {
                return NotFound();
            }

            var facture = await _context.Factures.FindAsync(id);
            if (facture == null)
            {
                return NotFound();
            }
            List<SelectListItem> listClients = new List<SelectListItem>();
            foreach(Client c in _context.Clients)
            {
                listClients.Add(new SelectListItem() { Text = c.Prenom + " " + c.Nom, Value = c.Id.ToString() });
            }
            listClients.Add(new SelectListItem() { Text = "Veuillez sélectionner un client", Value = "" });
            ViewData["ClientId"] = listClients;
            return View(facture);
        }

        // POST: Factures/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Numero,DateFacture,ClientId,Actif")] Facture facture)
        {
            if (id != facture.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(facture);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FactureExists(facture.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClientId"] = new SelectList(_context.Clients, "Id", "Localite", facture.ClientId);
            return View(facture);
        }

        // GET: Factures/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Factures == null)
            {
                return NotFound();
            }

            var facture = await _context.Factures
                .Include(f => f.Client)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (facture == null)
            {
                return NotFound();
            }

            return View(facture);
        }

        // POST: Factures/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Factures == null)
            {
                return Problem("Entity set 'MonContext.Factures'  is null.");
            }
            var facture = await _context.Factures.FindAsync(id);
            if (facture != null)
            {
                _context.Factures.Remove(facture);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FactureExists(int id)
        {
          return _context.Factures.Any(e => e.Id == id);
        }
    }
}

WebApplicationSolution/WebApplicationDemo2023/Views/Shared/Message.cshtml
@{
    if (TempData["messageOK"] != null && TempData["messageOK"] != "")
    {
        <div class="alert alert-success" role="alert">
            @TempData["messageOK"]
        </div>
    }
    if (TempData["messageKO"] != null && TempData["messageKO"] != "")
    {
        <div class="alert alert-danger" role="alert">
            @TempData["messageKO"]
        </div>
    }
    
}

WebApplicationSolution/WebApplicationDemo2023/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ma première application Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplicationDemo2023.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplicationDemo2023</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categorie" asp-action="Index">Catégories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="Index">Clients</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Factures" asp-action="Index">Factures</a>
                        </li>
                        @{
                            string role = User.Claims.FirstOrDefault(x => x.Type == "Role").Value;
                            if (role == "admin")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Article" asp-action="Index">Articles</a>
                                </li>
                            }

                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">
                                Se déconnecter (Salut @HttpContextAccessor.HttpContext.Session.GetString("userName"))</a>
                        </li>

                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApplicationDemo2023 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>